### ISSUE TITLE
Please add my kingdom!

### ISSUE THREAD

**Issue by reduviidae** [blockstack/animal-kingdom#149]
https://laughing-goldstine-172136.netlify.com

wiljagocook.id.blockstack

**Comment by moxiegirl** [comment]
@reduviidae your kingdom is blocked due to the cors error.  I can still add it but no one will be able to use it. Step 10 in this procedure explains how to fix this error:

https://docs.blockstack.org/develop/zero_to_dapp_3.html#deploy-your-dapp-on-the-web

Thank you for joining our clan! Your animal kingdom can be found listed in the clan here: https://animalkingdoms.netlify.com/others.  Please don't forget to submit your "Blockstack Sample Application" to https://app.co/ and claim your limited edition Zero-to-Dapp t-shirt.
